/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "v4.5-dev-2008-g90da43557f"
#endif /* AVUTIL_FFVERSION_H */
